services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    command: --innodb-buffer-pool-size=256M --max-connections=50
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    build: ./docker
    depends_on:
      - db
    ports:
      - "8082:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      # point WP to Redis for object caching
      WP_REDIS_HOST: redis
      # Performance optimizations
      WORDPRESS_CONFIG_EXTRA: |
        // Admin performance optimizations
        define('CONCATENATE_SCRIPTS', false);
        define('COMPRESS_SCRIPTS', false);
        define('COMPRESS_CSS', false);
        define('SCRIPT_DEBUG', false);
        define('WP_DEBUG', false);
        define('WP_DEBUG_LOG', false);
        define('WP_DEBUG_DISPLAY', false);
        // Disable plugin/theme editor
        define('DISALLOW_FILE_EDIT', true);
        // Reduce admin heartbeat
        define('WP_POST_REVISIONS', 3);
        // Increase memory for admin
        ini_set('memory_limit', '512M');
    volumes:
      # only uploads need persistence
      - ./wp_dir/wp-content/uploads:/var/www/html/wp-content/uploads

  redis:
    image: redis:6-alpine

volumes:
  db_data:
